### ISSUE TITLE
fix seed for random initialization of the SOM

### ISSUE THREAD

**Issue by oHunewald** [LCSB-BioCore/GigaSOM.jl#144]
**Summary**
fix seed for random initialization of the SOM

**Expected behavior**
re-producibility of the som clustering

**Comment by exaexa** [comment]
Just for the record, initGigaSOM can be now seeded manually with `seed=someNonNegativeInteger` or you can smash in a whole custom RNG as in `rng=MersenneTwister()`. All randomness is generated&used on the main node.
