### ISSUE TITLE
Adding CSV file import

### ISSUE THREAD

**Issue by oHunewald** [LCSB-BioCore/GigaSOM.jl#159]
Although GigaSOM was developed with its main focus on mass cytometry data, it could be used for any kind of multi-dimensional data clustering.

A commun file format as CSV would allow for other data to be imported.

**Comment by exaexa** [comment]
OK, that should be simple. (Let's add a normal binary formats too.)

Any other suggestions? (@laurentheirendt  )

**Comment by laurentheirendt** [comment]
for now only CSV I think 👍
