### ISSUE TITLE
remove deprecation warnings

### ISSUE THREAD

**Issue by laurentheirendt** [LCSB-BioCore/GigaSOM.jl#165]
These deprecation warnings are currently being thrown:
```
┌ Warning: `DataFrame(columns::AbstractMatrix)` is deprecated, use `DataFrame(columns, :auto)` instead.
│   caller = ip:0x0
└ @ Core :-1
```
Let's remove them 👍

**Comment by exaexa** [comment]
Kindof wondering if these things still occur (especially after I removed almost all DataFrames stuff). Perhaps this is solved now?

**Comment by laurentheirendt** [comment]
in the CI run one would see if they are still thrown or not

**Comment by exaexa** [comment]
ah wow, still there and I also discovered another warning :D
