### ISSUE TITLE
support for different distance metrics

### ISSUE THREAD

**Issue by cciccole** [LCSB-BioCore/GigaSOM.jl#68]
It'd be nice if there were better support for different distance metrics for training the SOM and mapping winners. It looks like this can be implemented easily by pass-through of a metric argument directly to the NearestNeighbors::BruteTree

**Comment by exaexa** [comment]
I was in fact planning to implement this "when I have a bit of time", the change is relatively straightforward. I'll submit a patch ASAP.

**Comment by laurentheirendt** [comment]
Thanks @cciccole for reporting and @exaexa for fixing! 👍

**Comment by cciccole** [comment]
👍
