### ISSUE TITLE
add sample_id to distributed file splitting

### ISSUE THREAD

**Issue by oHunewald** [LCSB-BioCore/GigaSOM.jl#84]
Adding a sample_id column to the splitted files or in a separated vector in each worker to re-construct the relation between the training data after splitting.

**Comment by laurentheirendt** [comment]
@oHunewald, still relevant?

**Comment by exaexa** [comment]
I guess this is still relevant although not that pressing. A standalone sample_id vector can be constructed manually using a tiny modification of the current data loading code. Guess we could just add a helper function?
